#!/bin/sh

# Copyright (c) 2019 Sorint.lab S.p.A.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
TMPFILE1=$(mktemp)
TMPFILE2=$(mktemp)
df -n | tr ':' ' ' |sort -k1 > "$TMPFILE1"
df -Pk | sed 1d | sort -k6 > "$TMPFILE2"
paste "$TMPFILE1" "$TMPFILE2" | awk ' { $1=""; t = $2; $2 = $3; $3 = t; $4 = $4*1024; $5 = $5*1024; $6 = $6*1024; print; } ' 
rm "$TMPFILE1"
rm "$TMPFILE2"

