#!/bin/sh
choice=$1
case $choice in
"start")
        cd /opt/ercole-agent-hpux
        sudo -u ercole sh -c "cd /opt/ercole-agent-hpux && nohup ./ercole-agent >>/var/adm/ercole-agent.log 2>&1 &"
        ;;
"stop")
        ps -ef|grep -i ercole-agent|grep -v grep|awk '{print $2}'|xargs -L1 kill -9 
        ;;
esac