#!/bin/sh

# Copyright (c) 2019 Sorint.lab S.p.A.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

HOSTNAME=$(hostname)
KERNEL=$(uname -s)
KERNEL_VERSION=$(uname -r)

OS=$(uname -o)
OS_VERSION=$(uname -v)
CPU_MODEL=$(kstat cpu_info | grep "brand" | cut -c34- | head -n 1)
CPU_SPEED=$(/usr/sbin/psrinfo -pv |  grep clock | sed 's/.* clock \([0-9]*\).*/\1/' | head -n 1)
SWP_TOTAL=$(top -d1 | grep -i "total swap" | cut -d',' -f3 | cut -d' ' -f2 | sed 's/[^0-9]*//g')
MEM_TOTAL=$(($(/usr/sbin/prtconf | grep "Memory" | sed -e 's/Memory size: \(.*\) Megabytes/\1/') / 1024))
CPU_THREAD=$(nproc --all)
if [ "$CPU_THREAD" = '1' ]; then
  CPU_CORES=1
  THREADS_PER_CORE=1  
else 
  CPU_CORES=$(($CPU_THREAD / 2))
  THREADS_PER_CORE=2
fi

SOCKET=$(/usr/sbin/psrinfo -p)

if [ "$SOCKET" -gt "$CPU_CORES" ]; then
  CORES_PER_SOCKET=1 
else 
  CORES_PER_SOCKET=$(($CPU_CORES / $SOCKET))
fi

CHECK_SUN_CLUSTER=$(ps -ef | grep -v grep | grep rpc.pmfd|wc -l)
if [ "$CHECK_SUN_CLUSTER" = 1 ]; then
  SUN_CLUSTER=Y
else
  SUN_CLUSTER=N
fi

CHECK_VERITAS_CLUSTER=$(ps -ef | grep -v grep | grep had|wc -l)
if [ "$CHECK_VERITAS_CLUSTER" = 1 ]; then
  VERITAS_CLUSTER=Y
else
  VERITAS_CLUSTER=N
fi

CHECK_ORACLE_CLUSTER=$(ps -ef | grep -v grep | grep crsd|wc -l)
if [ "$CHECK_ORACLE_CLUSTER" -gt 0 ]; then
  ORACLE_CLUSTER=Y
else
  ORACLE_CLUSTER=N
fi

 AIX_CLUSTER=N

TYPE=PH
VIRTUAL=N

echo "hostname: $HOSTNAME
cpumodel: $CPU_MODEL @ $CPU_SPEED MHz
cputhreads: $CPU_THREAD
cpucores: $CPU_CORES
cpufrequency: $CPU_SPEED MHz
cpusockets: $SOCKET
threadspercore: $THREADS_PER_CORE
corespersocket: $CORES_PER_SOCKET
type: $TYPE
virtual: $VIRTUAL
kernel: $KERNEL
kernelversion: $KERNEL_VERSION
os: $OS
osversion: $OS_VERSION
memorytotal: $MEM_TOTAL
swaptotal: $SWP_TOTAL
oraclecluster: $ORACLE_CLUSTER
veritascluster: $VERITAS_CLUSTER
suncluster: $SUN_CLUSTER
aixcluster: $AIX_CLUSTER" 
