#!/bin/ksh

# Copyright (c) 2019 Sorint.lab S.p.A.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

SID=$1
DBV=$2
TYPE=$3
HOME=$4

if [ -z "$SID" ]; then
  echo "Missing SID parameter"
  exit 1
fi

if [ -z "$TYPE" ]; then
  echo "Missing type parameter"
  exit 1
fi

if [ -z "$DBV" ]; then
  echo "Missing DBV parameter"
  exit 1
fi

if [ -z "$HOME" ]; then
  echo "Missing ORACLE_HOME parameter"
  exit 1
fi


ERCOLE_HOME=$(dirname "$0")
ERCOLE_HOME="$(dirname "$ERCOLE_HOME")"
ERCOLE_HOME="$(dirname "$ERCOLE_HOME")"

export ORAENV_ASK=NO
export ORACLE_SID=$SID
export ORACLE_HOME=$HOME
export PATH=$HOME/bin:$PATH


S_VERSION="select (case when UPPER(banner) like '%EXTREME%' then 'EXE' when UPPER(banner) like '%ENTERPRISE%' then 'ENT' else 'STD' end) as versione from v\$version where rownum=1;"

DB_VERSION=$(sqlplus -S / as sysdba << EOF
set pages 0 feedback off
${S_VERSION}
exit
EOF
)

DB_NAME=$(sqlplus -S / as sysdba << EOF
set pages 0 feedback off
select name from v\$database;
exit
EOF
)

DB_ONE=x$(sqlplus -S / as sysdba << EOF
set pages 0 feedback off
HOST srvctl config database -d $DB_NAME |grep -i One
exit
EOF
)



if [[ "$TYPE" = 'HPVRT' ]]
then
   VIRTUAL=Y
   CPU_THREAD=$(ioscan -fnk|grep proc|wc -l)
   CPU_CORES=$(($CPU_THREAD/2))
   SOCKET=1

  if [[ $DB_VERSION = 'EXE' || $DB_VERSION = 'ENT' ]]; then
    NUM_LICENSE=$(echo 0.5*$CPU_THREAD|bc)
    FACTOR=0.5
  elif [[ $DB_VERSION = 'STD' ]]; then
    NUM_LICENSE=$SOCKET
    FACTOR=$SOCKET
  fi
elif [ $TYPE = 'PH' ]
then

  VIRTUAL=N
  DIVISO=$(/usr/contrib/bin/machinfo |grep -i processor| grep logical| awk '{print $4}'| awk -F "(" '{print $2}')
  CPU_THREAD=$(/usr/contrib/bin/machinfo |grep -i processor| grep logical| awk '{print $1}')
  CPU_CORES=$(($CPU_THREAD/2))
  SOCKET=$(($CPU_THREAD / $DIVISO))


  if [[ $DB_VERSION = 'EXE' || $DB_VERSION = 'ENT' ]]; then
    NUM_LICENSE=$(echo 0.5*$CPU_THREAD|bc)
    FACTOR=0.5
  elif [[ $DB_VERSION = 'STD' ]]; then
    NUM_LICENSE=$SOKET
    FACTOR=$SOKET
  fi
fi


if [[ $DB_VERSION = 'EXE' ]]; then
  echo "Oracle EXE; $NUM_LICENSE;"
else
  echo "Oracle EXE;;"
fi
if [[ $DB_VERSION = 'ENT' ]]; then
  echo "Oracle ENT; $NUM_LICENSE;"
else
  echo "Oracle ENT;;"
fi
if [[ $DB_VERSION = 'STD' ]]; then
  echo "Oracle STD; $NUM_LICENSE;"
else
  echo "Oracle STD;;"
fi


if [ $DBV == "10" ] || [ $DBV == "9" ]; then
    sqlplus -S "/ AS SYSDBA" @${ERCOLE_HOME}/sql/license-10.sql $CPU_THREADS "$THREAD_FACTOR"
elif [ $DBV == "11" ]; then 
    sqlplus -S "/ AS SYSDBA" @${ERCOLE_HOME}/sql/license.sql $CPU_THREADS "$THREAD_FACTOR" $DB_ONE
else
IS_PDB=$(
    sqlplus -S / as sysdba <<EOF
set pages 0 feedback off timing off
SELECT CASE WHEN COUNT(*) > 0 THEN 'TRUE' WHEN count(*) = 0 THEN 'FALSE' END FROM v\$pdbs;
exit
EOF
)

if [ $IS_PDB == "TRUE" ]; then
    sqlplus -S "/ AS SYSDBA" @${ERCOLE_HOME}/sql/license_pluggable.sql $CPU_THREADS "$THREAD_FACTOR" $DB_ONE
else
    sqlplus -S "/ AS SYSDBA" @${ERCOLE_HOME}/sql/license.sql $CPU_THREADS "$THREAD_FACTOR" $DB_ONE
fi
fi