#!/bin/sh

# Copyright (c) 2019 Sorint.lab S.p.A.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

HOSTNAME=$(hostname)
KERNEL=AIX
KERNEL_VERSION=$(oslevel -s)

OS=AIX
OS_VERSION=$(uname -r -v)
CPU_MODEL=$(prtconf 2>/dev/null |grep roces|grep -i type | awk '{print $NF}')
CPU_SPEED=$(prtconf 2>/dev/null |grep roces|grep -i speed | awk -F ":" '{print $NF}' | tr -d ' ')

SWP_TOTAL=$(lsps -s|tail -1 | awk '{print $1}'|awk -F "M" '{print $1/1024}')
MEM_TOTAL=$(prtconf -m| awk '{print $3/1024}')

CPU_CORES=$(lscfg -vp|grep proc|wc -l)
CPU_THREAD=$(($CPU_CORES * 4))
THREADS_PER_CORE=4
CORES_PER_SOCKET=$CPU_CORES
SOCKET=1

CHECK_SUN_CLUSTER=$(ps -ef | grep -v grep | grep rpc.pmfd|wc -l)
if [ "$CHECK_SUN_CLUSTER" = 1 ]; then
  SUN_CLUSTER=Y
else
  SUN_CLUSTER=N
fi

CHECK_VERITAS_CLUSTER=$(ps -ef | grep -v grep | grep had|wc -l)
if [ "$CHECK_VERITAS_CLUSTER" = 1 ]; then
  VERITAS_CLUSTER=Y
else
  VERITAS_CLUSTER=N
fi

CHECK_ORACLE_CLUSTER=$(ps -ef | grep -v grep | grep crsd|wc -l)
if [ "$CHECK_ORACLE_CLUSTER" -gt 0 ]; then
  ORACLE_CLUSTER=Y
else
  ORACLE_CLUSTER=N
fi

if [ -f "/usr/sbin/cluster/clstat" ]; then
  AIX_CLUSTER=Y
else
  AIX_CLUSTER=N
fi

# CHECK_TYPE_SERVER_VMWARE=$(dmesg | grep VMware | wc -l)

# if [ "$CHECK_TYPE_SERVER_VMWARE" -gt 0 ]; then
#   TYPE=VMWARE
#   VIRTUAL=Y
# else
  TYPE=PH
  VIRTUAL=N
# fi

echo "hostname: $HOSTNAME
cpumodel: $CPU_MODEL
cputhreads: $CPU_THREAD
cpucores: $CPU_CORES
cpufrequency: $CPU_SPEED
cpusockets: $SOCKET
threadspercore: $THREADS_PER_CORE
corespersocket: $CORES_PER_SOCKET
type: $TYPE
virtual: $VIRTUAL
kernel: $KERNEL
kernelversion: $KERNEL_VERSION
os: $OS
osversion: $OS_VERSION
memorytotal: $MEM_TOTAL
swaptotal: $SWP_TOTAL
oraclecluster: $ORACLE_CLUSTER
veritascluster: $VERITAS_CLUSTER
suncluster: $SUN_CLUSTER
aixcluster: $AIX_CLUSTER" 
